import { User, LostFoundItem, Claim, AppNotification } from '../src/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-student-1',
    name: 'Abdul Riyan',
    email: 'abdulriyan.137748@marwadiuniversity.ac.in',
    role: 'student',
    studentOrStaffId: 'MU23CSE1048',
    department: 'Computer Science & Engineering (AI/ML)',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    phoneNumber: '+91 98765 43210',
    finderScore: 85,
    itemsReturnedCount: 3,
    verifiedHelpfulActionsCount: 4,
    createdAt: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'usr-student-2',
    name: 'Ananya Sharma',
    email: 'ananya.s@marwadiuniversity.ac.in',
    role: 'student',
    studentOrStaffId: 'MU23IT0412',
    department: 'Information Technology',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phoneNumber: '+91 98123 45678',
    finderScore: 92,
    itemsReturnedCount: 5,
    verifiedHelpfulActionsCount: 6,
    createdAt: '2026-08-20T11:30:00.000Z',
  },
  {
    id: 'usr-staff-1',
    name: 'Prof. Rajesh Kulkarni',
    email: 'rajesh.kulkarni@marwadiuniversity.ac.in',
    role: 'staff',
    studentOrStaffId: 'STF-FAC-882',
    department: 'Department of Computer Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phoneNumber: '+91 94220 11223',
    finderScore: 98,
    itemsReturnedCount: 8,
    verifiedHelpfulActionsCount: 9,
    createdAt: '2026-07-01T09:00:00.000Z',
  },
  {
    id: 'usr-admin-1',
    name: 'Campus Security & Lost Property Admin',
    email: 'admin.lostfound@marwadiuniversity.ac.in',
    role: 'admin',
    studentOrStaffId: 'ADM-SEC-001',
    department: 'Central Campus Administration & Security Desk',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    phoneNumber: '+91 90000 12345',
    finderScore: 100,
    itemsReturnedCount: 34,
    verifiedHelpfulActionsCount: 42,
    createdAt: '2026-01-10T08:00:00.000Z',
  },
];

export const INITIAL_ITEMS: LostFoundItem[] = [
  // Pair 1: Black Wallet
  {
    id: 'LST-2026-101',
    type: 'lost',
    title: 'Black Leather Men\'s Wallet',
    category: 'Wallet / Purse',
    description: 'Black bi-fold leather wallet with a small faint scratch on the bottom right corner. Contains a Metro card and some gym receipts.',
    date: '2026-10-03',
    approximateTime: '14:30',
    location: 'Central Library',
    buildingOrArea: '1st Floor Reading Room',
    color: 'Black',
    brand: 'WildHorn',
    distinguishingFeatures: 'Small scratch near coin compartment, dark grey stitching inside.',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'POTENTIAL_MATCH',
    userId: 'usr-student-1',
    userName: 'Abdul Riyan',
    userRole: 'student',
    userDepartment: 'CSE (AI/ML)',
    createdAt: '2026-10-03T15:10:00.000Z',
    updatedAt: '2026-10-03T16:00:00.000Z',
  },
  {
    id: 'FND-2026-201',
    type: 'found',
    title: 'Black Leather Bi-fold Wallet',
    category: 'Wallet / Purse',
    description: 'Found a black leather wallet under wooden desk #14 in the library reading section. Has minor wear and scratch on outer corner.',
    date: '2026-10-03',
    approximateTime: '15:45',
    location: 'Central Library',
    buildingOrArea: '1st Floor Reading Room',
    color: 'Black',
    brand: 'WildHorn / Genuine Leather',
    distinguishingFeatures: 'Corner surface scratch, card slots filled.',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'POTENTIAL_MATCH',
    userId: 'usr-student-2',
    userName: 'Ananya Sharma',
    userRole: 'student',
    userDepartment: 'IT',
    createdAt: '2026-10-03T16:00:00.000Z',
    updatedAt: '2026-10-03T16:00:00.000Z',
  },

  // Pair 2: Scientific Calculator
  {
    id: 'LST-2026-102',
    type: 'lost',
    title: 'Casio fx-991CW ClassWiz Scientific Calculator',
    category: 'Scientific Calculators',
    description: 'Black & white body Casio scientific calculator. Lost right after Mathematics for AI practical exam in block A.',
    date: '2026-10-04',
    approximateTime: '11:15',
    location: 'Academic Block A (CSE & IT)',
    buildingOrArea: 'AI & ML Lab 304',
    color: 'Black',
    brand: 'Casio',
    distinguishingFeatures: 'Has a small silver sticker on the sliding plastic cover reading "AR-09".',
    imageUrl: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'POTENTIAL_MATCH',
    userId: 'usr-student-1',
    userName: 'Abdul Riyan',
    userRole: 'student',
    userDepartment: 'CSE (AI/ML)',
    createdAt: '2026-10-04T12:00:00.000Z',
    updatedAt: '2026-10-04T12:45:00.000Z',
  },
  {
    id: 'FND-2026-202',
    type: 'found',
    title: 'Casio 991CW Calculator with Cover',
    category: 'Scientific Calculators',
    description: 'Found on the side table in Lab 304 after morning lab batch concluded. Kept safely in faculty room.',
    date: '2026-10-04',
    approximateTime: '12:30',
    location: 'Academic Block A (CSE & IT)',
    buildingOrArea: 'AI & ML Lab 304',
    color: 'Black',
    brand: 'Casio',
    distinguishingFeatures: 'Sliding hard cover attached with silver sticker.',
    imageUrl: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'POTENTIAL_MATCH',
    userId: 'usr-staff-1',
    userName: 'Prof. Rajesh Kulkarni',
    userRole: 'staff',
    userDepartment: 'CSE',
    createdAt: '2026-10-04T12:45:00.000Z',
    updatedAt: '2026-10-04T12:45:00.000Z',
  },

  // Pair 3: Blue Water Bottle
  {
    id: 'LST-2026-103',
    type: 'lost',
    title: 'Milton Thermosteel Blue Insulated Flask (750ml)',
    category: 'Water Bottles & Flasks',
    description: 'Deep cobalt blue stainless steel water bottle. Left on table near the outdoor juice bar during lunch break.',
    date: '2026-10-02',
    approximateTime: '13:30',
    location: 'Student Canteen & Food Court',
    buildingOrArea: 'Juice & Coffee Counter',
    color: 'Blue',
    brand: 'Milton',
    distinguishingFeatures: 'Slight dent at the stainless steel base bottom rim.',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'POTENTIAL_MATCH',
    userId: 'usr-student-2',
    userName: 'Ananya Sharma',
    userRole: 'student',
    userDepartment: 'IT',
    createdAt: '2026-10-02T14:00:00.000Z',
    updatedAt: '2026-10-02T14:40:00.000Z',
  },
  {
    id: 'FND-2026-203',
    type: 'found',
    title: 'Blue Stainless Steel Water Bottle',
    category: 'Water Bottles & Flasks',
    description: 'Found a 750ml blue metallic water flask on a patio table outside the food court canteen.',
    date: '2026-10-02',
    approximateTime: '14:15',
    location: 'Student Canteen & Food Court',
    buildingOrArea: 'Outdoor Pavilion',
    color: 'Blue',
    brand: 'Milton',
    distinguishingFeatures: 'Base rim shows slight dent.',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'POTENTIAL_MATCH',
    userId: 'usr-student-1',
    userName: 'Abdul Riyan',
    userRole: 'student',
    userDepartment: 'CSE (AI/ML)',
    createdAt: '2026-10-02T14:30:00.000Z',
    updatedAt: '2026-10-02T14:30:00.000Z',
  },

  // Pair 4: College ID Card
  {
    id: 'LST-2026-104',
    type: 'lost',
    title: 'Student Smart ID Card with Blue Lanyard',
    category: 'College ID Card',
    description: 'College RFID access card with university navy blue lanyard. Slipped out near security gates when boarding bus.',
    date: '2026-10-01',
    approximateTime: '17:15',
    location: 'Campus Bus Stand & Parking',
    buildingOrArea: 'Main Campus Gate Security',
    color: 'Blue',
    brand: 'Marwadi University RFID',
    distinguishingFeatures: 'Department code CSE-AIML visible, barcode on backside.',
    imageUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'CLAIMED',
    userId: 'usr-student-1',
    userName: 'Abdul Riyan',
    userRole: 'student',
    userDepartment: 'CSE (AI/ML)',
    createdAt: '2026-10-01T17:45:00.000Z',
    updatedAt: '2026-10-02T10:00:00.000Z',
  },
  {
    id: 'FND-2026-204',
    type: 'found',
    title: 'Student ID Card (CSE AIML Department)',
    category: 'College ID Card',
    description: 'Handed over by student who found it on pavement near Bus Bay 4. Deposited at Security Guard Cabin.',
    date: '2026-10-01',
    approximateTime: '17:30',
    location: 'Campus Bus Stand & Parking',
    buildingOrArea: 'Bus Bay 4-6',
    color: 'Blue',
    brand: 'University Official ID',
    distinguishingFeatures: 'Navy lanyard with university insignia.',
    imageUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'CLAIMED',
    userId: 'usr-admin-1',
    userName: 'Campus Security Admin',
    userRole: 'admin',
    userDepartment: 'Security Desk',
    createdAt: '2026-10-01T17:50:00.000Z',
    updatedAt: '2026-10-02T10:00:00.000Z',
  },

  // Pair 5: Wireless Earbuds (Returned)
  {
    id: 'LST-2026-105',
    type: 'lost',
    title: 'boAt Airdopes True Wireless Earbuds',
    category: 'Earphones & Headphones',
    description: 'Carbon black charging case with Type-C port. Lost during Tech Fest orientation session.',
    date: '2026-09-28',
    approximateTime: '16:00',
    location: 'Central Auditorium',
    buildingOrArea: 'Main Hall Seats',
    color: 'Black',
    brand: 'boAt',
    distinguishingFeatures: 'Has a small anime sticker outline on top lid.',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'RETURNED',
    userId: 'usr-student-2',
    userName: 'Ananya Sharma',
    userRole: 'student',
    userDepartment: 'IT',
    resolvedAt: '2026-09-30T14:00:00.000Z',
    returnedToUserId: 'usr-student-2',
    createdAt: '2026-09-28T16:30:00.000Z',
    updatedAt: '2026-09-30T14:00:00.000Z',
  },
  {
    id: 'FND-2026-205',
    type: 'found',
    title: 'boAt Wireless Earbuds Charging Case',
    category: 'Earphones & Headphones',
    description: 'Found under Row F seat 12 during post-event auditorium sweep.',
    date: '2026-09-28',
    approximateTime: '18:00',
    location: 'Central Auditorium',
    buildingOrArea: 'Main Hall Seats',
    color: 'Black',
    brand: 'boAt',
    distinguishingFeatures: 'Sticker outline on lid matches owner claim.',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'RETURNED',
    userId: 'usr-staff-1',
    userName: 'Prof. Rajesh Kulkarni',
    userRole: 'staff',
    userDepartment: 'CSE',
    resolvedAt: '2026-09-30T14:00:00.000Z',
    returnedToUserId: 'usr-student-2',
    createdAt: '2026-09-28T18:15:00.000Z',
    updatedAt: '2026-09-30T14:00:00.000Z',
  },

  // Additional single items
  {
    id: 'LST-2026-106',
    type: 'lost',
    title: 'Titan Fastrack Digital Sports Watch',
    category: 'Watches & Smartbands',
    description: 'Matte black silicone strap with red digital seconds indicator. Slipped off in badminton court during practice.',
    date: '2026-10-04',
    approximateTime: '08:30',
    location: 'Sports Complex & Gymnasium',
    buildingOrArea: 'Badminton Courts',
    color: 'Black',
    brand: 'Fastrack',
    distinguishingFeatures: 'Back cover has engraving FT-2023, strap buckle has small paint chip.',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'LOST',
    userId: 'usr-student-1',
    userName: 'Abdul Riyan',
    userRole: 'student',
    userDepartment: 'CSE (AI/ML)',
    createdAt: '2026-10-04T09:15:00.000Z',
    updatedAt: '2026-10-04T09:15:00.000Z',
  },
  {
    id: 'FND-2026-206',
    type: 'found',
    title: 'HP 65W Blue-Pin Laptop Adapter Charger',
    category: 'Laptops & Chargers',
    description: 'Found plugged into wall socket on 2nd floor corridor bench near seminar room 3.',
    date: '2026-10-04',
    approximateTime: '13:00',
    location: 'Academic Block B (Mech & Civil)',
    buildingOrArea: 'Seminar Hall 3',
    color: 'Black',
    brand: 'HP',
    distinguishingFeatures: 'Three-pin power cable with yellow rubber cable organizer wrap.',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'FOUND',
    userId: 'usr-staff-1',
    userName: 'Prof. Rajesh Kulkarni',
    userRole: 'staff',
    userDepartment: 'CSE',
    createdAt: '2026-10-04T13:30:00.000Z',
    updatedAt: '2026-10-04T13:30:00.000Z',
  },
  {
    id: 'FND-2026-207',
    type: 'found',
    title: 'Metal Bike & Dorm Keychain with Red Ribbon',
    category: 'Keys & Keychains',
    description: 'Ring with 2 silver keys and 1 brass padlock key. Red cloth tag attached.',
    date: '2026-10-04',
    approximateTime: '16:00',
    location: 'Campus Bus Stand & Parking',
    buildingOrArea: 'Student 2-Wheeler Parking',
    color: 'Red',
    brand: 'Godrej / Honda',
    distinguishingFeatures: 'Red ribbon tag has text "REMOVE BEFORE FLIGHT".',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80',
    contactPreference: 'portal_only',
    status: 'FOUND',
    userId: 'usr-student-2',
    userName: 'Ananya Sharma',
    userRole: 'student',
    userDepartment: 'IT',
    createdAt: '2026-10-04T16:20:00.000Z',
    updatedAt: '2026-10-04T16:20:00.000Z',
  }
];

export const INITIAL_CLAIMS: Claim[] = [
  {
    id: 'CLM-2026-001',
    itemId: 'FND-2026-204',
    itemTitle: 'Student ID Card (CSE AIML Department)',
    itemType: 'found',
    claimantId: 'usr-student-1',
    claimantName: 'Abdul Riyan',
    claimantEmail: 'abdulriyan.137748@marwadiuniversity.ac.in',
    claimantStudentId: 'MU23CSE1048',
    claimantDepartment: 'Computer Science & Engineering (AI/ML)',
    uniqueFeatureProof: 'Student ID number MU23CSE1048 matches my official university portal registration. Blood group O+ printed on front.',
    approximatePurchaseInfo: 'Issued during Fall 2023 semester orientation by Student Affairs Desk.',
    itemContentsProof: 'University lanyard has small silver badge clip.',
    privateDescription: 'Official ID card with my photo, issued by Dean office.',
    additionalEvidence: 'Can present DigiLocker student card and ERP profile on my mobile phone at the security cabin.',
    status: 'pending',
    createdAt: '2026-10-02T10:00:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'usr-student-1',
    title: 'High AI Match Detected! (94%)',
    message: 'A Black Leather Bi-fold Wallet found in Central Library strongly matches your lost report LST-2026-101.',
    type: 'match',
    read: false,
    link: '/items/FND-2026-201',
    createdAt: '2026-10-03T16:05:00.000Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-student-1',
    title: 'Potential Match for Calculator (96%)',
    message: 'Prof. Rajesh Kulkarni reported a found Casio 991CW in Lab 304 matching your report LST-2026-102.',
    type: 'match',
    read: false,
    link: '/items/FND-2026-202',
    createdAt: '2026-10-04T12:50:00.000Z',
  },
  {
    id: 'notif-3',
    userId: 'usr-student-2',
    title: 'Return Verified +25 Finder Score!',
    message: 'Your safe return of boAt Earbuds to owner was approved by Campus Security. Your Finder Score is now 92.',
    type: 'return',
    read: true,
    link: '/finder-score',
    createdAt: '2026-09-30T14:05:00.000Z',
  },
  {
    id: 'notif-4',
    userId: 'usr-admin-1',
    title: 'New Ownership Claim Submitted',
    message: 'Abdul Riyan submitted a verification claim for Student ID Card (FND-2026-204).',
    type: 'claim',
    read: false,
    link: '/admin',
    createdAt: '2026-10-02T10:02:00.000Z',
  },
];
